function ECKVisualise_gap_trial(dc, hdr, dta, parent)

    %% init
    % init global vars
    evFilterOut = {};
    evTimes = {};
    evLab = {};
    evGapCols = [];
    
    filterOutEvents = {...
        'GAP_TRIAL_ONSET',...
        'GAP_TRIAL_OFFSET',...
        'ADDAOI'};
    
    showAoIs = {...
        'GAPCS',...
        'GAPPS'};

    % get metadata
    mdStr = sprintf('%s',...
        dc.Data{1}.ParticipantID);

    %% plot
    % positions
    posParent = get(parent, 'Position');

    plotGaze(dc, parent, [.03, 0.25, 1, .97], filterOutEvents, showAoIs)
    
    % table
    cols = cell2mat(...
            cellfun(@(x) find(strcmpi(hdr, x)),...
                {'ValidTrial',...
                'ValidGazeOnCS',...
                'ValidGazeOnCsAtPSOnset',...
                'ValidGazeToPS1200',...
                'ValidGazeToPsOppo1200',...
                'ValidGazeToPS200',...
                'ValidGazeStuckOnCs',...
                'CSGazeSkipped',...
                'PSGazeSkipped'},...
                'Uniform', 0));
            
    % flags for valid and skipped
    valid = dta{cols(1)};
    skipped = dta{cols(8)} & dta{cols(9)};
    
    if valid
        valState = 'VALID';
        valCol = [.7, 1, .7];
    else
        valState = 'INVALID';
        valCol = [1, .7, .7];
    end
    
    if skipped
        skipState = 'SKIPPED';
        skipCol = [1, .7, .7];
    else
        skipState = '';
    end
    
    table = uitable('Parent', parent,...
        'Units', 'normalized',...
        'Position', [0, 0, 1, .25],...
        'BackgroundColor', valCol,...
        'ColumnName', [],...
        'RowName', [],...
        'ColumnWidth', num2cell(repmat(140, 1, length(cols))),...
        'Data', [hdr(cols); dta(:, cols)]);

end