function val = etPropValBuffer(mainBuffer)

    lVal = ...
        mainBuffer(:, 7) ~= -1 &...
        mainBuffer(:, 8) ~= -1 &...
        ~isnan(mainBuffer(:, 7)) &...
        ~isnan(mainBuffer(:, 8));
    
    rVal = ...
        mainBuffer(:, 20) ~= -1 &...
        mainBuffer(:, 21) ~= -1 &...
        ~isnan(mainBuffer(:, 20)) &...
        ~isnan(mainBuffer(:, 21));
    
    val = sum(lVal | rVal) / size(mainBuffer, 1);

end